### ISSUE TITLE
theres a problem

### ISSUE THREAD

**Issue by epic8009** [RamiLego4Game/LIKO-12#121]

**Comment by Positive07** [comment]
So, what's the problem?

Don't do this kind of things please, post your issue and format it decently. 
No one can guess what you tried to say

**Comment by RamiLego4Game** [comment]
@Positive07 epic is known for his sillyness, just ignore him.

**Comment by Positive07** [comment]
Pretty sure you could block him from comenting in the repo settings, or he could flood the issue tracker with this stuff

**Comment by RamiLego4Game** [comment]
I warned him in discord @Positive07
